### ISSUE TITLE
Getting Error on Deployment in Portainer/Raspbi 4

### ISSUE THREAD

**Issue by nicedevil007** [RaymondMouthaan/node-red-docker#18]
Hey Raymond,

first, thank you for your work on the 20.8 with compatibility for the raspberrys.

I have a small prob with your docker image and don't know how to fix it.

![grafik](https://user-images.githubusercontent.com/17103076/65370993-2f97eb80-dc5f-11e9-895d-565cda376c94.png)

I just took the original docker container from node-red and replaced the image with yours.

That were the original settings:

![grafik](https://user-images.githubusercontent.com/17103076/65371005-55bd8b80-dc5f-11e9-92ad-25b22f4d53e3.png)

**Comment by nicedevil007** [comment]
2nd test with a completly fresh new container for testing and without any command/entrypoint setup by myself I'm getting this:

![grafik](https://user-images.githubusercontent.com/17103076/65372172-c1f2bc00-dc6c-11e9-960b-d9073952d905.png)

**Comment by RaymondMouthaan** [comment]
@nicedevil007, thanks for testing my new image.

I have investigated your issue and I have a few ideas where it goes wrong. 

### OCI Runtime create failed
This is because the original Node-RED docker image uses both an `Entry Point` and `Command`. This is not the case for my images. In the screenshot below you can see it only uses `Entry Point`

Like you did for your test container, I recommend to start a new container instead of modifying the original.

![Screen Shot 2019-09-22 at 09 47 03](https://user-images.githubusercontent.com/25717738/65384086-55d09080-dd1e-11e9-90ff-9626cf9d4e6d.png)

### Permission denied
I assume you have your flows persistent on the host - looks like the node-red user hasn't got the access rights to write to this directory. 

The official image has a `node-red`user inside the container with uid `1000` and gid `1000`, so all your files/dirs in /data are created with uid `1000` and gid `1000`. 

You can verify this using on the host:

```bash
$ ls -nal <path_to_your_node_red_persistent_dir>
```

However my images have a `node-red` user with uid `1001` and gid `1001` (this is because `1000:1000` has been assigned to the `node` user, which also exists inside the container). 

This means the original created files and dirs with `1000:1000` are not changeable by `1001:1001`.

There are a few solutions to make it work:

1. Run container with user 1000
Using portainer - enter in the Command & Logging section for the user `1000`, this means node-red runs with uid 1000 and therefore has permissions to access your persistent directory on the host.

![Screen Shot 2019-09-22 at 10 52 14](https://user-images.githubusercontent.com/25717738/65384827-4e61b500-dd27-11e9-876b-00f3ddbf3d2c.png)

From the command-line:

```bash
docker run -d --user 1000 -p1880:1880 -v <path_to_persistent_dir>:/data raymondmm/node-red:latest
```

2. Change access permissions on the host
Another solution is to change permissions on the persistent dir, so that "everyone" can read/write/execute on this directory.

```bash
chmod -R 777 <path_to_your_node_red_persistent_dir>
```

Regarding the permission issue, i am realising that it might affect a lot of node-red docker users once they use my images or when finally my PR [#127](https://github.com/node-red/node-red-docker/pull/127) gets merged. So I'll look into this to have it solved otherwise without affecting all users.

Hope this fixed your issue for now.

Greets,
Ray

**Comment by RaymondMouthaan** [comment]
@nicedevil007, you can ignore my previous post. I've fixed the permission issue in latest docker images. 

Make sure you pull the latest when you create a new container. 

### From portainer:
![Screen Shot 2019-09-22 at 14 13 24](https://user-images.githubusercontent.com/25717738/65387047-3dbf3800-dd43-11e9-995e-334f4ca8549c.png)

### From command line:
```bash
docker pull raymondmm/node-red:<tag_you_prefer> 
```
For all tags available and there description, please refer to [here](https://github.com/RaymondMouthaan/node-red-docker#image-variations).

**Comment by RaymondMouthaan** [comment]
I'll close this issue now, but don't hesitate to reopen if you are still facing issues.

**Comment by nicedevil007** [comment]
problem still exist :/

![grafik](https://user-images.githubusercontent.com/17103076/65393765-4b95ad00-dd85-11e9-9720-6ec5d08c00a5.png)

and yeah you are right, I'm using persistent directories for my data... my old container used the root user for this and if your image creates it's folders by itself in my bind directory like this:

![grafik](https://user-images.githubusercontent.com/17103076/65393813-0d4cbd80-dd86-11e9-85b0-5d2fc9bfcab0.png)

these folders got the same user/group:

![grafik](https://user-images.githubusercontent.com/17103076/65393818-1ccc0680-dd86-11e9-82c7-7171a9e07fa6.png)

**Comment by nicedevil007** [comment]
what I noticed as well:

![grafik](https://user-images.githubusercontent.com/17103076/65394279-f741fb80-dd8b-11e9-9c66-9fd87a145cd2.png)

It is using arm-v7 instead of 8 on raspberry pi 4?

I was pulling node-red:latest-12

**Comment by RaymondMouthaan** [comment]
@nicedevil007, have you tried to change the dirs + files on your host to user 1000:1000 (which is normally the pi user and group)?

```bash
sudo chown -R /docker/node-red-test
```

what do you get when you run on your PI4:

```bash
uname -m
```

**Comment by nicedevil007** [comment]
Hey Raymond, thank you for your response!
Will report back, I'm at work right now and don't have much spare time to test :)

But arm32v7... yeah it is depending on the usage of dietpi that is using 32v7 on my pi 4 :/
```
root@DietPi:~# uname -m
armv7l
```

The Docker Version I'm using is the same:
```
root@DietPi:/docker# docker --version
Docker version 19.03.1, build 74b1e89
```

**Comment by nicedevil007** [comment]
Ok... now it seems to run <3
